# Use postgres/example user/password credentials
version: '3.8'

volumes:
  database-data:

networks:
  stack:
    name: stack
    external: false

services:
  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file: .env
    networks:
      - stack

  calcom:
    image: calcom/cal.com:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_WEBAPP_URL: https://calendar.fluxosmm.com
        NEXT_PUBLIC_LICENSE_CONSENT: ${NEXT_PUBLIC_LICENSE_CONSENT}
        CALCOM_TELEMETRY_DISABLED: ${CALCOM_TELEMETRY_DISABLED}
        NEXTAUTH_SECRET: tdh1tblayy6kw0q7vbf3365bj7y354ik
        CALENDSO_ENCRYPTION_KEY: dms1ix8en2bipklkdyt9lgncv38fhj1e
        DATABASE_URL: postgresql://clvref07z0dkgaup756no9w9z:SUzxgCMzKmk4DCMqHM1oeJRe@clvref08301afp7aur68c6jyg:5432/clvref0800dkiaup7bl7s5mtd
        DATABASE_DIRECT_URL: postgresql://clvref07z0dkgaup756no9w9z:SUzxgCMzKmk4DCMqHM1oeJRe@clvref08301afp7aur68c6jyg:5432/clvref0800dkiaup7bl7s5mtd
      network: stack
    restart: always
    networks:
      - stack
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://clvref07z0dkgaup756no9w9z:SUzxgCMzKmk4DCMqHM1oeJRe@clvref08301afp7aur68c6jyg:5432/clvref0800dkiaup7bl7s5mtd
      - DATABASE_DIRECT_URL=postgresql://clvref07z0dkgaup756no9w9z:SUzxgCMzKmk4DCMqHM1oeJRe@clvref08301afp7aur68c6jyg:5432/clvref0800dkiaup7bl7s5mtd
    depends_on:
      - database

